### ISSUE TITLE
tmpop: add block signatures to segment evidences

### ISSUE THREAD

**Issue by such** [stratumn/go-indigocore#131]
### Expected behavior
The evidence of a Segment should be enough to allow a complete validation. 

### Actual behavior
The only missing piece are the signatures of the validator nodes on the block.

**Comment by simonvadee** [comment]
the pre-commits of a block, containing the validators public keys and signatures, are not currently available in the ABCI (only the LastCommitHash contained in the header passed to BeginBlock is). A discussion is taking place on tendermint's forum (https://cosmos.rocket.chat/channel/development?msg=pQByczFAAAQZsRtDY).

**Comment by such** [comment]
I was thinking that maybe we should not store anything like the block header and the block pre commit signatures since they are already store by Tendermint Core. We could only store the block height and enrich segments in tmstore with the header and the signatures when they are requested.
What do you think?

**Comment by simonvadee** [comment]
I thought the goal of an evidence was to make it possible to verify the validity of a segment independently from the tendermint network. However, without an access to the blockchain, there is no way of telling if the evidence was made up or not, so you have a good point. Technically, the block height is not even needed to recover the block in which a segment was included though, why do we need it for ?

**Comment by such** [comment]
What I meant was:
If we know the block height then anytime a segment is retrieved all proofs we're interested in to independently validate it was included in the blockchain can be added to it.
A complete segment, with a full evidence, can then be provided to anyone that has no access to the blockchain.

**Comment by simonvadee** [comment]
In the case where a segment is saved on two distinct tendermint blockchains, it is only possible to give a full evidence if the originalProof (originalHeader, merkleProof, signatures, signedTrustedTimestamp) is provided for both blockchains right ? If we chose to enrich the segment at query-time, this is only possible if a node(=actor) is part of both networks, which will not be the case most of the time. What do you think ?

**Comment by simonvadee** [comment]
Therefore we have to decide between :

- "light evidence" option : when saving a segment, only the block height is stored ; proof data (original header and merkle proof + current header and merkle proof + validators signatures for both blocks) will be added to the evidence when querying this segment. This option will cause a loss of performance for segment queries and some savings in terms of storage. To implement this, we have to wait till [this](https://github.com/tendermint/iavl/pull/1) is merged and released.

- "full evidence" option : corresponds to what is currently implemented, except that the validators signatures for the original header will be added when saving a segment. Current proof (signatures, header, merkle proof) will obviously still be added at query time. To implement this, we need to wait till evidence/voteInfo is passed to the ABCI through BeginBlock (currently on the [roadmap](https://github.com/tendermint/tendermint/blob/master/CHANGELOG.md), @ebuchman said it was [coming soon](https://cosmos.rocket.chat/channel/tendermint_core?msg=L4rtABcu8zpMsEED4)

**Comment by such** [comment]
This will probably be addressed in stratumn/sdk#191

**Comment by t-bast** [comment]
Tendermint recommends using their *lite* package that gets all the signature data and validates it.
We should investigate this (it requires updating our Tendermint version).
