### ISSUE TITLE
store: findSegments tags with regexp

### ISSUE THREAD

**Issue by jeremie-stratumn** [stratumn/go-indigocore#205]
### Expected behavior
`findSegments` accepts tags regular expression / wildcards, eg `'myTagFor*` should match tags like `'myTagForFiltering', 'myTagForSearching'...`
### Actual behavior
`findSegments` via tag filtering expect a full match when comparing a segment's tags and the filter's tags, eg: `'myTagForFiltering'=='myTagForFiltering'`.

**Comment by simonvadee** [comment]
@jeremie-stratumn  do we really need that ? we already added a Prefix and Suffix search. (closing for now)
