### ISSUE TITLE
tmstore: better handling of "duplicate" links

### ISSUE THREAD

**Issue by such** [stratumn/go-indigocore#296]
Currently TMStore rejects duplicates transactions with: 
```
time="2017-12-14T14:22:49Z" level=error msg="Failed to handle request" error="ABCI{code:BadNonce, data:, log:Duplicate transaction (ignored)}" method=POST origin="172.24.0.6:57388" status=500 url=/links
```

We probably don't want to allow saving two different segments with the same linkHash so it's fine that this doesn't work. The error handling could be a bit better though.

**Comment by simonvadee** [comment]
deprecated
