### ISSUE TITLE
cs: serialize link.meta

### ISSUE THREAD

**Issue by simonvadee** [stratumn/go-indigocore#332]
In order to avoid casts as much as we can, the `link.meta` should be serialized in a go object instead of `map[string]interface{}`. However, we should still have the ability to add custom fields (depending on the use-case for which the indigo sdk is used). 

```golang
type LinkMeta struct {
    MapID string
    Process string
    Action string
    Type string
    Inputs []string
    Refs []*Reference // we should also come up with a serialisation for references
    Tags []string
    PrevLinkHash string
    Data map[string]interface{} //customizable fields
}
```

Implementation of SRP X is a good occasion to make that change

**Comment by alexppxela** [comment]
+1
